# DankSearch Configuration
# See https://github.com/AvengeMedia/danksearch for documentation

index_path = "/home/nighmared/.cache/danksearch/index"
listen_addr = ":43654"
max_file_bytes = 2097152
worker_count = 4
text_extensions = [".txt", ".md", ".go", ".py", ".js", ".ts", ".jsx", ".tsx", ".json", ".yaml", ".yml", ".toml", ".html", ".css", ".rs", ".c", ".cpp", ".h", ".java", ".rb", ".php", ".sh", ".kdl", ".dart", ".fish", ".htoprc", ".gitconfig", ".nanorc", ".ssh-config", ".service", ".conf", ".jsonc"]
index_all_files = true
auto_reindex = false
reindex_interval_hours = 24
extract_exif =true

[[index_paths]]
# hack to prevent indexing android skd >.< 
  path = "/home/nighmared/Android"
  max_depth = 1
  exclude_hidden = true
  exclude_dirs = ["Sdk"]

[[index_paths]]
  path = "/home/nighmared/Documents/projects/dotter"
  max_depth = 3
  exclude_hidden = false
  exclude_dirs = [".git"]

[[index_paths]]
  path = "/home/nighmared"
  max_depth = 0
  exclude_hidden = true
  exclude_dirs = ["node_modules", "bower_components", ".npm", ".yarn", "site-packages", "__pycache__", ".venv", "venv", ".tox", ".pytest_cache", ".eggs", "dist", "build", "out", "bin", "obj", "target", "vendor", ".gradle", ".m2", "bundle", ".cache", ".parcel-cache", ".next", ".nuxt", ".serverless", "Library", ".Trash-1000", ".postgresql", ".postgres", ".mysql", ".mongodb", ".redis", "pgdata", "pg_data", "go", ".cargo", ".pyenv", ".rbenv", ".nvm", ".rustup", ".composer", ".gem", ".idea", ".vscode", ".git"]



