[helpers]


[default.files]

[alacritty.files]
alacritty = "~/.config/alacritty/alacritty.toml"

[atuin.files]
atuin = "~/.config/atuin/config.toml"

[code.files]
code-keybindings = "~/.config/Code/User/keybindings.json"
code-settings = "~/.config/Code/User/settings.json"

[fish.files]
fish = "~/.config/fish/config.fish"
fish-atuin = "~/.config/fish/conf.d/atuin.env.fish"
fish-grepir = "~/.config/fish/conf.d/grepir.fish"
fish-kubectl = "~/.config/fish/conf.d/kubectl.fish"
fish-z = "~/.config/fish/conf.d/z.fish"
fish_variables = "~/.config/fish/fish_variables"
fish_plugins = "~/.config/fish/fish_plugins"

[git.files]
git = "~/.config/git/config"
git-eth = "~/Documents/ETH/gitconfig"
git-vis = "~/Documents/vis/gitconfig"

[htop.files]
htop = "~/.config/htop/htoprc"

[nano.files]
nano = "~/.config/nano/nanorc"

[ssh.files]
ssh = "~/.ssh/config"
ssh_thesis = "~/.ssh/thesis_cscs"

[ssh.variables]
raava_remote_key = "a"


[vlc.files]
vlcrc = "~/.config/vlc/vlcrc"

[niri.files]
niri = "~/.config/niri/config.kdl"

[mako.files]
mako = "~/.config/mako/config"

[waybar.files]
waybar = "~/.config/waybar/config.jsonc"
waybar-style = "~/.config/waybar/style.css"

[swaylock.files]
swaylock = "~/.config/swaylock/config"

[swaybg.files]
swaybg = "~/.config/systemd/user/swaybg.service"

[helix.files]
helix = "~/.config/helix/config.toml"

[settings]
default_target_type = "automatic"
