[helpers]


[default.files]

[alacritty.files]
"alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[atuin.files]
"atuin.toml" = "~/.config/atuin/config.toml"

[code.files]
"code-keybindings.json" = "~/.config/Code/User/keybindings.json"
"code-settings.json" = "~/.config/Code/User/settings.json"

[dms.files]
"dsearch.toml" = "~/.config/danksearch/config.toml"
"dms.json" ="~/.config/DankMaterialShell/settings.json"

[fish.files]
"fish.fish" = "~/.config/fish/config.fish"
"fish-atuin.fish" = "~/.config/fish/conf.d/atuin.env.fish"
"fish-grepir.fish" = "~/.config/fish/conf.d/grepir.fish"
"fish-kubectl.fish" = "~/.config/fish/conf.d/kubectl.fish"
"fish-z.fish" = "~/.config/fish/conf.d/z.fish"
"fish_variables.fish" = "~/.config/fish/fish_variables"
"fish_plugins.txt" = "~/.config/fish/fish_plugins"

[git.files]
"git.gitconfig" = "~/.config/git/config"
"git-eth.gitconfig" = "~/Documents/ETH/gitconfig"
"git-vis.gitconfig" = "~/Documents/vis/gitconfig"

[htop.files]
"htop.htoprc" = "~/.config/htop/htoprc"

[nano.files]
"nano.nanorc" = "~/.config/nano/nanorc"

[ssh.files]
"ssh.ssh-config" = "~/.ssh/config"
"ssh_thesis.ssh-config" = "~/.ssh/thesis_cscs"

[ssh.variables]
raava_remote_key = "a"


[vlc.files]
"vlcrc.conf" = "~/.config/vlc/vlcrc"

[niri.files]
"niri.kdl" = "~/.config/niri/config.kdl"

[mako.files]
"mako.toml" = "~/.config/mako/config"

[waybar.files]
"waybar.jsonc" = "~/.config/waybar/config.jsonc"
"waybar-style.css" = "~/.config/waybar/style.css"

[swaylock.files]
"swaylock.conf" = "~/.config/swaylock/config"

[swaybg.files]
"swaybg.service" = "~/.config/systemd/user/swaybg.service"

[helix.files]
"helix.toml" = "~/.config/helix/config.toml"

[settings]
default_target_type = "automatic"
