includes = [".dotter/includes/yangchen-vars.toml"]
packages = [
    "alacritty",
    "atuin",
    "code",
    "dms",
    "fish",
    "git",
    "htop",
    "mako",
    "nano",
    "niri",
    "ssh",
    "vlc",
    "waybar",
    "swaylock",
    "swaybg",
    "helix",
]

# [files]

# [variables]


# [ssh.variables]
