includes = [".dotter/includes/yangchen-vars.toml"]
packages = [
    "alacritty",
    "atuin",
    "code",
    "fish",
    "git",
    "htop",
    "nano",
    "niri",
    "ssh",
    "vlc",
]

# [files]

# [variables]


# [ssh.variables]
